name: Manual Recon

on:
  workflow_dispatch:
    inputs:
      domain:
        description: "Enter target domain (e.g. example.com)"
        required: true
        type: string

jobs:
  recon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y curl poppler-utils
          go install github.com/tomnomnom/assetfinder@latest
          go install github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          go install github.com/projectdiscovery/httpx/cmd/httpx@latest
          go install github.com/projectdiscovery/katana/cmd/katana@latest
          go install github.com/lc/gau/v2/cmd/gau@latest
          go install github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest
          go install github.com/PentestPad/subzy@latest

      - name: Save Domain to File
        run: echo "${{ github.event.inputs.domain }}" > target.txt

      - name: Run Recon Tool
        run: go run bugbountyauto.go

      - name: Send final-result.txt to Discord
        if: always()
        run: |
          curl -F "payload_json={\"content\":\"Recon completed ✅ for domain: ${{ github.event.inputs.domain }}\"}" \
               -F "file=@final-result.txt" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
